replicaCount: 1
image:
  repository: myrepo/my-service
  tag: "latest"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 3000
env: {}
secretEnv: {}
namespace: mern-backend
resources:
  requests:
    cpu: "10m"
    memory: "64Mi"
  limits:
    cpu: "100m"
    memory: "128Mi"
