# ProductCatalog HTTPRoute â€” two rules, PathPrefix + Exact
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: productcatalog-route
  namespace: {{ .Release.Namespace }}
  labels:
    app: productcatalogservice
    {{- include "hipstershop.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: {{ .Values.global.gateway.name }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api/products/
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /products/
    backendRefs:
    - name: productcatalogservice
      port: {{ .Values.global.ports.productcatalogservice }}
  - matches:
    - path:
        type: Exact
        value: /api/products
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplaceFullPath
          replaceFullPath: /products
    backendRefs:
    - name: productcatalogservice
      port: {{ .Values.global.ports.productcatalogservice }}

