apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hipster
  name: paymentservice
  labels:
    app: paymentservice
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: savitxr/paymentservice-hipster:latest
        ports:
        - containerPort: 50051
        envFrom:
        - configMapRef:
            name: hipster-config
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: service-ports
              key: PAYMENTSERVICE_PORT
        - name: DISABLE_PROFILER
          valueFrom:
            configMapKeyRef:
              name: app-features
              key: PAYMENT_SERVICE_DISABLE_PROFILER
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-users
              key: PAYMENT_MONGO_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-users
              key: PAYMENT_MONGO_PASSWORD
        - name: MONGO_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: PAYMENT_DB_NAME
        - name: MONGO_PAYMENTS_COLLECTION
          valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: PAYMENT_CHARGES_COLLECTION
        - name: MONGO_URI
          value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongodb-0.mongo-headless.hipster.svc.cluster.local:27017,mongodb-1.mongo-headless.hipster.svc.cluster.local:27017,mongodb-2.mongo-headless.hipster.svc.cluster.local:27017/payment_db?replicaSet=rs0&authSource=payment_db&authMechanism=SCRAM-SHA-256"
        readinessProbe:
          httpGet:
            path: "/_healthz"
            port: 50051
        livenessProbe:
          httpGet:
            path: "/_healthz"
            port: 50051
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  namespace: hipster
  name: paymentservice
  labels:
    app: paymentservice
spec:
  type: ClusterIP
  selector:
    app: paymentservice
  ports:
  - name: http
    port: 50051
    targetPort: 50051


