apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-product
  namespace: mern-db
spec:
  serviceName: "mongo-product"
  replicas: 1
  selector:
    matchLabels:
      app: mongo-product
  template:
    metadata:
      labels:
        app: mongo-product
    spec:
      containers:
      - name: mongo
        image: mongo:6.0
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-product
  namespace: mern-db
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongo-product
  clusterIP: None
