apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  namespace: {{ .Release.Namespace }}
  labels:
    app: loadgenerator
    {{- include "hipstershop.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.global.replicas.loadgenerator }}
  selector:
    matchLabels:
      app: loadgenerator
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      containers:
      - name: load-generator
        image: {{ .Values.global.images.loadgenerator }}
        command: ["/bin/sh"]
        args:
        - -c
        - |
          while true; do
            wget -q -O- http://frontend.{{ .Release.Namespace }}.svc.cluster.local/
            sleep 0.1
          done
        resources:
          requests:
            cpu: {{ .Values.global.resources.standard.requests.cpu }}
            memory: {{ .Values.global.resources.standard.requests.memory }}
          limits:
            cpu: {{ .Values.global.resources.standard.limits.cpu }}
            memory: {{ .Values.global.resources.standard.limits.memory }}
      restartPolicy: Always

