apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  namespace: {{ .Release.Namespace }}
  labels:
    app: adservice
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
spec:
  replicas: {{ .Values.global.replicas.adservice }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.global.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.global.rollingUpdate.maxSurge }}
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: {{ .Values.global.images.adservice }}
        ports:
        - containerPort: {{ .Values.global.ports.adservice }}
        envFrom:
        - configMapRef:
            name: hipster-config
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: service-ports
              key: ADSERVICE_PORT
        resources:
          requests:
            cpu: {{ .Values.global.resources.adservice.requests.cpu }}
            memory: {{ .Values.global.resources.adservice.requests.memory }}
          limits:
            cpu: {{ .Values.global.resources.adservice.limits.cpu }}
            memory: {{ .Values.global.resources.adservice.limits.memory }}
        readinessProbe:
          initialDelaySeconds: 60
          periodSeconds: 15
          httpGet:
            path: "/_healthz"
            port: {{ .Values.global.ports.adservice }}
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 15
          httpGet:
            path: "/_healthz"
            port: {{ .Values.global.ports.adservice }}
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
      - name: tmp-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
  namespace: {{ .Release.Namespace }}
  labels:
    app: adservice
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
spec:
  type: ClusterIP
  selector:
    app: adservice
  ports:
  - name: http
    port: {{ .Values.global.ports.adservice }}
    targetPort: {{ .Values.global.ports.adservice }}

