apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-cart
  namespace: hipster
spec:
  serviceName: mongodb-cart-headless
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-cart
  template:
    metadata:
      labels:
        app: mongodb-cart
    spec:
      containers:
      - name: mongodb
        image: mongo:6.0
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: data
          mountPath: /data/db
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "nfs"
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-cart-headless
  namespace: hipster
spec:
  clusterIP: None
  selector:
    app: mongodb-cart
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-cart
  namespace: hipster
spec:
  selector:
    app: mongodb-cart
  ports:
  - port: 27017
    targetPort: 27017
