apiVersion: v1
kind: Secret
metadata:
  namespace: hipster
  name: mongodb-root
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: mongoadmin
  MONGO_ROOT_PASSWORD: mongoadminpass

---
apiVersion: v1
kind: Secret
metadata:
  namespace: hipster
  name: mongodb-users
type: Opaque
stringData:
  AUTH_MONGO_USERNAME: authuser
  AUTH_MONGO_PASSWORD: authpassword
  CART_MONGO_USERNAME: cartuser
  CART_MONGO_PASSWORD: cartpassword
  CATALOG_MONGO_USERNAME: cataloguser
  CATALOG_MONGO_PASSWORD: catalogpassword
  ORDER_MONGO_USERNAME: orderuser
  ORDER_MONGO_PASSWORD: orderpassword
  PAYMENT_MONGO_USERNAME: paymentuser
  PAYMENT_MONGO_PASSWORD: paymentpassword
  NOTIFICATION_MONGO_USERNAME: notificationuser
  NOTIFICATION_MONGO_PASSWORD: notificationpassword
  ANALYTICS_MONGO_USERNAME: analyticsuser
  ANALYTICS_MONGO_PASSWORD: analyticspassword
