apiVersion: v1
kind: Secret
metadata:
  namespace: hipster
  name: mongodb-root
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: REPLACE_WITH_MONGO_ROOT_USERNAME
  MONGO_ROOT_PASSWORD: REPLACE_WITH_MONGO_ROOT_PASSWORD

---
apiVersion: v1
kind: Secret
metadata:
  namespace: hipster
  name: mongodb-users
type: Opaque
stringData:
  AUTH_MONGO_USERNAME: REPLACE_WITH_AUTH_MONGO_USERNAME
  AUTH_MONGO_PASSWORD: REPLACE_WITH_AUTH_MONGO_PASSWORD
  CART_MONGO_USERNAME: REPLACE_WITH_CART_MONGO_USERNAME
  CART_MONGO_PASSWORD: REPLACE_WITH_CART_MONGO_PASSWORD
  CATALOG_MONGO_USERNAME: REPLACE_WITH_CATALOG_MONGO_USERNAME
  CATALOG_MONGO_PASSWORD: REPLACE_WITH_CATALOG_MONGO_PASSWORD
  ORDER_MONGO_USERNAME: REPLACE_WITH_ORDER_MONGO_USERNAME
  ORDER_MONGO_PASSWORD: REPLACE_WITH_ORDER_MONGO_PASSWORD
  PAYMENT_MONGO_USERNAME: REPLACE_WITH_PAYMENT_MONGO_USERNAME
  PAYMENT_MONGO_PASSWORD: REPLACE_WITH_PAYMENT_MONGO_PASSWORD
  NOTIFICATION_MONGO_USERNAME: REPLACE_WITH_NOTIFICATION_MONGO_USERNAME
  NOTIFICATION_MONGO_PASSWORD: REPLACE_WITH_NOTIFICATION_MONGO_PASSWORD
  ANALYTICS_MONGO_USERNAME: REPLACE_WITH_ANALYTICS_MONGO_USERNAME
  ANALYTICS_MONGO_PASSWORD: REPLACE_WITH_ANALYTICS_MONGO_PASSWORD
