apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  namespace: {{ .Release.Namespace }}
  labels:
    app: paymentservice
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
spec:
  replicas: {{ .Values.global.replicas.paymentservice }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.global.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.global.rollingUpdate.maxSurge }}
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: {{ .Values.global.images.paymentservice }}
        ports:
        - containerPort: {{ .Values.global.ports.paymentservice }}
        envFrom:
        - configMapRef:
            name: hipster-config
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: service-ports
              key: PAYMENTSERVICE_PORT
        - name: DISABLE_PROFILER
          valueFrom:
            configMapKeyRef:
              name: app-features
              key: PAYMENT_SERVICE_DISABLE_PROFILER
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-users
              key: PAYMENT_MONGO_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-users
              key: PAYMENT_MONGO_PASSWORD
        - name: MONGO_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: PAYMENT_DB_NAME
        - name: MONGO_PAYMENTS_COLLECTION
          valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: PAYMENT_CHARGES_COLLECTION
        - name: MONGO_URI
          value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongodb-0.mongo-headless.{{ .Release.Namespace }}.svc.cluster.local:27017,mongodb-1.mongo-headless.{{ .Release.Namespace }}.svc.cluster.local:27017,mongodb-2.mongo-headless.{{ .Release.Namespace }}.svc.cluster.local:27017/{{ .Values.global.mongodb.users.payment.database }}?replicaSet={{ .Values.global.mongodb.replicaSetName }}&authSource={{ .Values.global.mongodb.users.payment.database }}&authMechanism=SCRAM-SHA-256"
        readinessProbe:
          httpGet:
            path: "/_healthz"
            port: {{ .Values.global.ports.paymentservice }}
        livenessProbe:
          httpGet:
            path: "/_healthz"
            port: {{ .Values.global.ports.paymentservice }}
        resources:
          requests:
            cpu: {{ .Values.global.resources.standard.requests.cpu }}
            memory: {{ .Values.global.resources.standard.requests.memory }}
          limits:
            cpu: {{ .Values.global.resources.standard.limits.cpu }}
            memory: {{ .Values.global.resources.standard.limits.memory }}
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  namespace: {{ .Release.Namespace }}
  labels:
    app: paymentservice
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
spec:
  type: ClusterIP
  selector:
    app: paymentservice
  ports:
  - name: http
    port: {{ .Values.global.ports.paymentservice }}
    targetPort: {{ .Values.global.ports.paymentservice }}

